/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.game.client;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ram
 */
public class ImagePanel extends javax.swing.JPanel {
 private Image image;
private final int width=25;
private final int height=25;
 public static void main(String args[]){
    JFrame j= new JFrame();
    j.setBounds(5, 5, 50, 50);
    j.add(new ImagePanel(10,10));
    j.setVisible(true);
 }
    /**
     * Creates new form Fly
     */
    public ImagePanel(int x,int y) {
        try {       
           this.setBounds(x, y, width, height);
          Image sclaedImage = ImageIO.read(new File("/Users/Ram/Desktop/alive.jpg"));
          image =sclaedImage.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
      initComponents();
         this.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        } catch (Exception ex) {
            // handle exception...
       }
    }

 
 @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, null);
       
       
        
// see javadoc for more info on the parameters            
    }
     private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {  
          Random rand = new Random();
        JOptionPane.showMessageDialog(null, "My Goodness, this is so concise");
        this.repaint(rand.nextInt(40)+width, rand.nextInt(30)+width, width, height);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
